config/routes.rb
Rails.application.routes.draw do
  root 'requests#new'

  resources :requests, only: [:new, :create] do
    collection do
      post :contact, action: "contact"
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true, uniqueness: true

  after_create { self.delay.add_to_mailchimp_segment }

  def self.create_from_user params
    user = User.find_by_email(params[:email])
    user = User.create(params) if user.nil?
    Request.where("user_id = ?", user.id).first_or_create(user_id: user.id)
  end

  def add_to_mailchimp_segment
    if !Rails.env.test?
      begin
        Gibbon::API.lists.subscribe(id: ENV["MAILCHIMP_LIST_ID"], email: {email: self.user.email}, merge_vars: {FNAME: self.user.first_name, LNAME: self.user.last_name}, double_optin: false, update_existing: true)
        Gibbon::API.lists.static_segment_members_add(id: ENV["MAILCHIMP_LIST_ID"], seg_id: ENV["MAILCHIMP_SEGMENT_ID"], batch: [{email: self.user.email}])
      rescue Exception => e
        Rails.logger.error e
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests

  def self.create params
    if Rails.env.production? || Rails.env.staging?
      begin
        url = "#{ENV["ACCOUNTS_HOST"]}/users.json"
        user_hash = { first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: SecureRandom.hex, application_slug: "eufaco", ip: params[:ip] }
        body = { token: ENV["ACCOUNTS_API_TOKEN"], user: user_hash }
        response = HTTParty.post(url, body: body.to_json, headers: { 'Content-Type' => 'application/json' })
        logger.info response.inspect
        User.find_by_id(response['id'])
      rescue Exception => e
        logger.error e.message
      end
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < InheritedResources::Base

  def create
    params[:ip] = request.remote_ip
    request = Request.create_from_user(request_params)

    RequestMailer.delay.we_received_your_request(request)
    RequestMailer.delay.membership_card_requested(request)

    redirect_to root_path(anchor: "share")
  end

  def contact
    RequestMailer.delay.contact(params)
    redirect_to root_path(anchor: "contact"), notice: "Sua mensagem foi enviada. Obrigado pelo seu contato, vamos te responder o mais rápido possível!"
  end

  private

  def request_params
    params.permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_faq.html.slim
h2 FAQ [Meu Rio Eu Faço]
h3 1. O que é o Meu Rio Eu Faço?
p É o programa de celebração dos membros que fazem a Rede Meu Rio acontecer, seja fazendo contruibuição em dinheiro ou doando seu tempo e talento nas mobilizações. As vitórias conquistadas pela Rede são para benefício de todos, transformando o Rio em um lugar melhor, logo, nada mais justo que toda a cidade festeje quem está fazendo isso acontecer. Assim, a Rede Meu Rio foi buscar parceiros que têm a cara da cidade para pensar em modos diferentes de celebrar a sua participação, como meio de dizer o quanto ela é importante!

h3 2. Como funcionam as celebrações?
p Cada parceiro celebra nossos doadores e voluntários de uma maneira diferente. As celebrações são alguns mimos que variam entre descontos, brindes e outras surpresas que são concedidas aos membros da Rede Meu Rio no momento da visita ao local. Fique de olho também para eventos especiais!

h3 3. Ah, entendi! É tipo um clube de vantagens?
p Não! As experiências desenhadas nessas celebrações não visam benefícios, nem vantagens propriamente ditas. São apenas modos diferentes que os parceiros da Rede Meu Rio encontraram para dar aquele abraço em quem está fazendo a diferença através da Rede, sacou?

h3 4. Como faço para ser celebrado?
p Você pode ser celebrado se tornando um financiador da Rede através do #{link_to 'Faça Acontecer', 'http://facaacontecer.meurio.org.br', target: :blank} ou conquistando a medalha ‘Eu Faço’ realizando tarefas voluntárias através do #{link_to 'Multitude', 'http://multitude.meurio.org.br', target: :blank}.

h3 5. Como faço para obter a medalha ‘Eu Faço’?
p Para ganhar essa medalha, é necessário estar cadastrado no Multitude e ter acumulado no mínimo 360 minutos de tarefas realizadas de qualquer natureza.

h3 6. Quanto tempo demora para eu receber a minha carteirinha?
p Nas condições normais de temperatura e pressão, postaremos a sua carteirinha em até 30 dias após a solicitação.

h3 7. Qual o tempo de validade da carteirinha?
p As carteirinhas têm o prazo de 1 ano de validade a partir da data de emissão.

h3 8. Pedi a minha carteirinha e ela não chegou, o que eu faço?
p Caso isso aconteça, fale com a Fernanda através do email:  financiador@meurio.org.br

h3 9. Os parceiros são sempre os mesmos?
p De forma alguma! Nossa cidade é muito grande e estamos sempre à procura de novos parceiros que busquem fazer da cidade um lugar mais bacana e incentivem quem faz a diferença. Queremos celebrar nossos membros ao redor de todo o Rio, e com as mais diversas experiências!

h3 10. Como faço para me tornar um parceiro da Rede Meu Rio?
p Ficamos muito felizes com seu interesse! Para se tornar um parceiro basta enviar um email para contato@meurio.org.br e retornaremos para marcando uma data para um bate papo.

h3 Se quiser fazer alguma outra pergunta, fale com a Fernanda através do formulário de contato no final da página.

app/views/layouts/application.html.slim
html
  head
    title Meu Rio Eu Faço
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta property="og:title" content=t("share.facebook.title")
    meta property="og:description" content=t("share.facebook.description")
    meta property="og:image" content=image_url("facebook-share.jpg")
    meta property="og:url" content=request.url
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false'
    = csrf_meta_tags
  body
    <div id="fb-root"></div>
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    footer
      <div class="fb-like" data-href="https://www.facebook.com/meurio" data-width="360" data-show-faces="true" data-send="false" data-colorscheme="dark">

app/views/requests/new.html.slim
.slide-1
  .row
    .wraper= image_tag("meurio-eu-faco.png", class: "meurio-eu-faco")
  .row
    .step
      = link_to image_tag("step-1.png"), 'http://facaacontecer.meurio.org.br', target: :blank
      span
        | Você contribui com
        br
        | a Rede Meu Rio
    .step
      = link_to image_tag("step-2.png"), 'http://meurio.org.br', target: :blank
      span
        | Nossas vitórias ajudam a
        br
        | construir uma cidade melhor
    .step
      = image_tag("step-3.png")
      span
        | A cidade festeja a
        br
        | sua participação!
  .row
    .wraper.medium
      .form-wraper
        .row
          .disclaimer
            | Já é nosso financiador ou conquistou a medalha #{link_to '"Eu Faço!"', "#faq", id: 'view_faq', "data-reveal-id" => "faq", "data-reveal" => true}?
            br
            | Solicite agora mesmo a sua carteirinha e seja celebrado!
        = form_for @request, html: { "data-abide" => true } do |form|
          .row
            .first_name_field
              = text_field_tag :first_name, nil, placeholder: "Nome", required: true
            .last_name_field
              = text_field_tag :last_name, nil, placeholder: "Sobrenome", required: true
            .email_field
              = email_field_tag :email, nil, placeholder: "Email", required: true
            .submit_button
              = form.submit "Solicitar Carteirinha", id: 'request-submit-button', class: [:button, :radius]

.slide-2
  .row
    .wraper
      h2 Meu Rio Eu Faço!
      p A Rede Meu Rio festeja a participação de quem faz a diferença na construção da cidade que todos merecemos. Contribua com a sua doação ou com o seu tempo e talento e desfrute de experiências únicas com parceiros e membros da nossa Rede que têm a cara do Rio.

.slide-3
  .row
    .wraper
      h2 Como funciona?
      p Torne-se financiador com Faça Acontecer ou conquiste a medalha "Eu Faço!" no Multitude e seja festejado por nossos parceiros. Comece agora mesmo!  Clique #{link_to 'aqui', "#faq", "data-reveal-id" => "faq", "data-reveal" => true} para mais detalhes.
  .row
    .multitude
      .image= image_tag("multitude.png")
      = link_to "Participe!", 'http://multitude.meurio.org.br', class: [:button, :radius], target: :blank
    .faca-acontecer
      .image= image_tag("facaacontecer.png")
      = link_to "Participe!", 'http://facaacontecer.meurio.org.br', class: [:button, :radius], target: :blank

.slide-4
  .row
    .wraper
      h2 Celebrações do momento
      p.lead A partir de 1˚ de Maio
  .row
    .celebration
      .image-wraper
        .icon-1= image_tag("icon-pins.png", title: 'Visite para ser celebrado!')
        .icon-2= image_tag("icon-gift.png", title: 'Uma surpresa para você!')
        .image= image_tag("celebrations/baianacica.jpg")
      .text
        h3 Baiana Ciça
        .description
          p A Ciça sempre quis conhecer o Rio. Há 11 anos, veio para passar um mês acabou não indo mais embora. Montou sua barraca na Praça XV quando não tinha quase nada por lá, sendo pioneira na revitalização do local. Carioquíssima e baiana, agora ela ajuda a Rede Meu Rio a celebrar quem faz a diferença na cidade dando um presentinho doce pros financiadores e voluntários que visitam sua barraca.
          p
            strong Endereço:
            br
            | Praça XV, do lado do Arco do Teles
          p
            strong Horários:
            br
            | Terças, Quintas e Sábados, a partir das 17h
    .celebration
      .image-wraper
        .icon-1= image_tag("icon-pins.png", title: 'Visite para ser celebrado!')
        .icon-2= image_tag("icon-gift.png", title: 'Uma surpresa para você!')
        .image= image_tag("celebrations/casadatata.jpg")
      .text
        h3 Da Casa da Táta
        .description
          p Não vamos te enganar: o Álvaro e a Táta são sérios concorrentes a melhores anfitriões do mundo. De sorriso sempre aberto e com alguns dos quitutes mais gostosos do Rio, é difícil não se sentir à vontade na Casa da Táta. Além disso, eles também festejam o trabalho da nossa Rede: o financiador ou voluntário que passar por lá vai descobrir como!
          p
            strong Endereço:
            br
            | Rua Professor Manoel Ferreira, nº 89 - Gávea
          p
            strong Horários:
            br
            | Segunda a Sexta, de 08h às 20h; Sábados de 08h às 18h30 e Domingos de 09h às 14h
    .celebration
      .image-wraper
        .icon-1= image_tag("icon-pins.png", title: 'Visite para ser celebrado!')
        .icon-2= image_tag("icon-coin.png", title: 'Preço diferenciado!')
        .image= image_tag("celebrations/surfrio.jpg")
      .text
        h3 SurfRio
        .description
          p O Fábio Andrade, educador físico, é o cara por trás das aulas de Surf e Stand Up Paddle no posto 6 de Copa e do Arpoador. Também fundou a APROSUP que desde 2011 tenta regulamentar o ensino e a prática do SUP para trazer mais segurança a todos. Graças a ele, nossas celebrações estão também no cenário mais amado pelos cariocas: a praia! Visite uma das barracas do SurfRio e saiba como!
          p
            strong Endereço:
            br
            | Posto 6 - Praia de Copacabana
          p
            strong Horários:
            br
            | Segunda a Sexta, de 08h às 16h e Sábados e Domingos de 08h às 10h
    .celebration
      .image-wraper
        .icon-1= image_tag("icon-pins.png", title: 'Visite para ser celebrado!')
        .icon-2= image_tag("icon-coin.png", title: 'Preço diferenciado!')
        .icon-3= image_tag("icon-calendar.png", title: 'Evento especial!')
        .image= image_tag("celebrations/casaporto.jpg")
      .text
        h3 Casa Porto
        .description
          p Raphael Vidal, idealizador de um dos centros culturais mais maneiros da Zona Portuária, abriu as portas da Casa Porto para a Rede Meu Rio! O espaço promove cursos, shows, palestras e cineclubes, além de contar com uma galeria de arte e um café/bistrô. No berço da identidade cultural carioca, o financiador e o voluntário da Rede serão celebrados com toda a riqueza da cultura local!
          p
            strong Endereço:
            br
            | Largo de São Francisco da Prainha, 4 - Sobrado
          p
            strong Horários:
            br
            | Segunda a Sexta, de 10h às 22h e Sábados e Domingos de 10h às 14
    .celebration
      .image-wraper
        .icon-1= image_tag("icon-pins.png", title: 'Visite para ser celebrado!')
        .icon-2= image_tag("icon-gift.png", title: 'Uma surpresa para você!')
        .image= image_tag("celebrations/browniedoluiz.jpg")
      .text
        h3 Brownie do Luiz
        .description
          p O Luiz fez de uma de suas paixões, o brownie, um incrível sucesso! Não apenas porque o bolinho é delicioso, mas também porque sua doçura permeia todo o trabalho que a equipe faz. O carinho e seriedade dessa galera são tão grandes que eles até criaram o Sustentabilibrownie. Agora o financiador e o voluntário do Meu Rio ganham um carinho especial: visite o BDL e descubra como seu dia pode ficar mais doce!
          p
            strong Endereço:
            br
            | Rua das Laranjeiras, 103 - Laranjeiras
          p
            strong Horários:
            br
            | Segunda a Sexta, de 10h às 18h e Sábados de 10h às 16h


.slide-5
  .row
    .wraper
      #map_canvas{data-pin-coin=image_url("pin-coin.png") data-pin-calendar=image_url("pin-calendar.png") data-pin-gift=image_url("pin-gift.png") data-pin-pins=image_url("pin-pins.png")}

.slide-6#contact
  .row
    - if notice
      .successful-contact
        = image_tag('icon-letter.png')
        h2= notice
    - else
      .wraper
        h2 Entre em contato
        p Quer saber mais sobre o Meu Rio Eu Faço? Ou se tornar um parceiro? É só dar um alô!
        = form_tag contact_requests_path, {id: "contact-form", "data-abide" => true}
          .contact-name-field
            = label_tag "contact_name", "Nome"
            = text_field_tag "contact_name", nil, required: true
          .contact-email-field
            = label_tag "contact_email", "Email"
            = text_field_tag "contact_email", nil, required: true, pattern: "email"
          .contact-subject-field
            = label_tag "contact_subject", "Assunto"
            = text_field_tag "contact_subject", nil, required: true
          .contact-message-field
            = label_tag "contact_message", "Mensagem"
            = text_area_tag "contact_message", nil, required: true
          = submit_tag "Enviar mensagem", id: "contact-submit-button", class: [:button, :radius]

#share.medium.reveal-modal{data-reveal}
  p.lead Recebemos o seu pedido! Em até 30 dias, a sua carteirinha será entregue e você vai poder curtir nossas celebrações.
  p Agora que você já faz parte da festa, convide os seus amigos a se tornarem financiadores da Rede Meu Rio! Clique nos botões abaixo para compartilhar o link do Faça Acontecer e trazer mais financiadores para a nossa Rede. Juntos, vamos festejar um Rio cada vez mais lindo!
  = link_to "Compartilhe no Facebook", "https://www.facebook.com/sharer/sharer.php?u=#{URI::encode('http://bit.ly/eufacoacontecer')}", class: ["button", "facebook-share"]
  = link_to "Compartilhe no Twitter", "https://twitter.com/share?url=#{URI::encode('http://bit.ly/eufacoacontecer')}&text=#{URI::encode(t("share.twitter.tweet"))}", class: ["button", "twitter-share"]
  a.close-reveal-modal &#215;

#faq.medium.reveal-modal{data-reveal}
  = render 'layouts/faq'
  a.close-reveal-modal &#215;